// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.3.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ClassLibrary_Service1.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("APIApplication")]
    public partial class APIApplicationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "APIApplication", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Get API respnse using given endpoint")]
        [NUnit.Framework.CategoryAttribute("Test1")]
        public virtual void GetAPIRespnseUsingGivenEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "Test1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get API respnse using given endpoint", null, tagsOfScenario, argumentsOfScenario);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    testRunner.Given("RestService \"getemployees\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table21.AddRow(new string[] {
                            "Version",
                            "1"});
                table21.AddRow(new string[] {
                            "Cval",
                            "Accept"});
#line 7
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table21, "And ");
#line hidden
#line 11
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table22.AddRow(new string[] {
                            "address.street",
                            "Kulas Light"});
                table22.AddRow(new string[] {
                            "address.geo.lng",
                            "81.1496"});
                table22.AddRow(new string[] {
                            "name",
                            "Leanne Graham"});
                table22.AddRow(new string[] {
                            "website",
                            "hildegard.org"});
#line 12
 testRunner.Then("verify following response values", ((string)(null)), table22, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post createuser API respnse using given endpoint")]
        [NUnit.Framework.CategoryAttribute("Test2")]
        public virtual void PostCreateuserAPIRespnseUsingGivenEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "Test2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post createuser API respnse using given endpoint", null, tagsOfScenario, argumentsOfScenario);
#line 22
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 23
  testRunner.Given("RestService \"createuser\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table23.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
#line 24
 testRunner.And("I call \"POST\" service with modified parameter", ((string)(null)), table23, "And ");
#line hidden
#line 27
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table24.AddRow(new string[] {
                            "name",
                            "morpheus"});
                table24.AddRow(new string[] {
                            "job",
                            "leader"});
#line 28
 testRunner.Then("verify following response values", ((string)(null)), table24, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Multiple API respnse using given endpoint")]
        [NUnit.Framework.CategoryAttribute("Test3")]
        public virtual void MultipleAPIRespnseUsingGivenEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "Test3"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Multiple API respnse using given endpoint", null, tagsOfScenario, argumentsOfScenario);
#line 34
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 35
    testRunner.Given("RestService \"getemployees\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table25.AddRow(new string[] {
                            "Version",
                            "1"});
                table25.AddRow(new string[] {
                            "Cval",
                            "Accept"});
#line 36
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table25, "And ");
#line hidden
#line 40
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table26.AddRow(new string[] {
                            "name",
                            "Leanne Graham"});
                table26.AddRow(new string[] {
                            "website",
                            "hildegard.org"});
#line 41
 testRunner.Then("verify following response values", ((string)(null)), table26, "Then ");
#line hidden
#line 46
    testRunner.Given("RestService \"test1\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table27.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
                table27.AddRow(new string[] {
                            "Version",
                            "1"});
#line 47
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table27, "And ");
#line hidden
#line 51
  testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table28.AddRow(new string[] {
                            "userId",
                            "1"});
                table28.AddRow(new string[] {
                            "id",
                            "1"});
                table28.AddRow(new string[] {
                            "title",
                            "delectus aut autem"});
                table28.AddRow(new string[] {
                            "completed",
                            "False"});
#line 52
      testRunner.Then("verify following response values", ((string)(null)), table28, "Then ");
#line hidden
#line 59
  testRunner.Given("RestService \"employeetype\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table29.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
                table29.AddRow(new string[] {
                            "Version",
                            "1"});
#line 60
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table29, "And ");
#line hidden
#line 64
  testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table30.AddRow(new string[] {
                            "userId",
                            "1"});
                table30.AddRow(new string[] {
                            "id",
                            "1"});
                table30.AddRow(new string[] {
                            "title",
                            "delectus aut autem"});
                table30.AddRow(new string[] {
                            "completed",
                            "False"});
#line 65
      testRunner.Then("verify following response values", ((string)(null)), table30, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Post and  Get API 1 using given endpoint")]
        [NUnit.Framework.CategoryAttribute("Test4")]
        public virtual void PostAndGetAPI1UsingGivenEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "Test4"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post and  Get API 1 using given endpoint", null, tagsOfScenario, argumentsOfScenario);
#line 74
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 75
    testRunner.Given("RestService \"createuser\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table31.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
#line 76
 testRunner.And("I call \"POST\" service with modified parameter", ((string)(null)), table31, "And ");
#line hidden
#line 79
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table32.AddRow(new string[] {
                            "name",
                            "morpheus"});
                table32.AddRow(new string[] {
                            "job",
                            "leader"});
#line 80
 testRunner.Then("verify following response values", ((string)(null)), table32, "Then ");
#line hidden
#line 85
 testRunner.Given("RestService \"getemployees\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table33.AddRow(new string[] {
                            "Version",
                            "1"});
                table33.AddRow(new string[] {
                            "Cval",
                            "Accept"});
#line 86
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table33, "And ");
#line hidden
#line 90
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table34.AddRow(new string[] {
                            "name",
                            "Leanne Graham"});
                table34.AddRow(new string[] {
                            "website",
                            "hildegard.org"});
#line 91
 testRunner.Then("verify following response values", ((string)(null)), table34, "Then ");
#line hidden
#line 96
    testRunner.Given("RestService \"test1\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table35.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
                table35.AddRow(new string[] {
                            "Version",
                            "1"});
#line 97
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table35, "And ");
#line hidden
#line 101
  testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table36.AddRow(new string[] {
                            "userId",
                            "1"});
                table36.AddRow(new string[] {
                            "id",
                            "1"});
                table36.AddRow(new string[] {
                            "title",
                            "delectus aut autem"});
                table36.AddRow(new string[] {
                            "completed",
                            "False"});
#line 102
      testRunner.Then("verify following response values", ((string)(null)), table36, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Both Get and Post API 2  using given endpoint")]
        [NUnit.Framework.CategoryAttribute("Test5")]
        public virtual void BothGetAndPostAPI2UsingGivenEndpoint()
        {
            string[] tagsOfScenario = new string[] {
                    "Test5"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Both Get and Post API 2  using given endpoint", null, tagsOfScenario, argumentsOfScenario);
#line 110
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 111
    testRunner.Given("RestService \"createuser\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table37.AddRow(new string[] {
                            "contenttype",
                            "application/json"});
#line 112
 testRunner.And("I call \"POST\" service with modified parameter", ((string)(null)), table37, "And ");
#line hidden
#line 115
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table38.AddRow(new string[] {
                            "name",
                            "morpheus"});
                table38.AddRow(new string[] {
                            "job",
                            "leader"});
#line 116
 testRunner.Then("verify following response values", ((string)(null)), table38, "Then ");
#line hidden
#line 121
    testRunner.Given("RestService \"getemployees\" with config in \"ServiceDetail\" file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Veriable",
                            "Value"});
                table39.AddRow(new string[] {
                            "Version",
                            "1"});
                table39.AddRow(new string[] {
                            "Cval",
                            "Accept"});
#line 122
 testRunner.And("I call \"GET\" service with modified parameter", ((string)(null)), table39, "And ");
#line hidden
#line 126
 testRunner.And("verify response should return \"OK\" as statuscode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "nodePath",
                            "value"});
                table40.AddRow(new string[] {
                            "name",
                            "Leanne Graham"});
                table40.AddRow(new string[] {
                            "website",
                            "hildegard.org"});
#line 127
 testRunner.Then("verify following response values", ((string)(null)), table40, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
